### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by superours** [pmneila/PyMCubes#6] opened 2016-03-21 13:21 UTC
python setup.py build >>
running build_py
running build_ext
building 'mcubes._mcubes' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c mcubes/src/_mcubes.c -o build/temp.linux-x86_64-2.6/mcubes/src/_mcubes.o -std=c++11
gcc: mcubes/src/_mcubes.c: No such file or directory
gcc: no input files
error: command 'gcc' failed with exit status 1

**Comment by pmneila** [comment] 2016-03-23 04:34
Hi @superours,

Unfortunately I cannot reproduce this error. Are you using a recent version of Cython/distutils/setuptools? It looks like you are using Python 2.6, which is pretty old. You should try a more recent version such as 2.7 or 3.

**Comment by superours** [comment] 2016-03-30 15:56
It works now! You were right, I tried with the latest version of Python, Cython, Numpy, g++ and it is fine now. Thank you.

**Comment by pmneila** [comment] 2016-03-30 15:57
Great! I'm closing the issue then.

**Closed by pmneila** 2016-03-30 15:57 UTC
